name: Update add-on
description: Update an NVDA add-on
title: "[Add-on]: "

body:
  - type: markdown
    attributes:
      value: |
        Thanks for sending this add-on!
  - type: input
    id: name
    attributes:
      label: Add-on name
      description: Internal name of the add-on
      placeholder: clipContentsDesigner
    validations:
      required: true
  - type: input
    id: author
    attributes:
      label: Author
      description: Add-on authors
      placeholder: Jon Doe
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Add-on version
      placeholder: 16.1
    validations:
      required: true
  - type: input
    id: repo
    attributes:
      label: Repository
      description: Add-on repository
      placeholder: https://github.com/nvdaes/placeMarkers
    validations:
      required: true
  - type: input
    id: key
    attributes:
      label: Key
      description: Key in get.php
      placeholder: ccd
    validations:
      required: true
- type: checkboxes
    id: updateDev
    attributes:
      label: Dev link like stable
      description: The destination link for dev is like stable
      options:
        - label: The destination for dev and stable download links are the same
    validations:
      required: false
