name: Update add-on
description: Update an NVDA add-on
title: "Updated add-on"

body:
  - type: markdown
    attributes:
      value: |
        Thanks for sending this add-on!
  - type: input
    id: name
    attributes:
      label: Add-on name
      description: Internal name of the add-on
      placeholder: clipContentsDesigner
    validations:
      required: true
  - type: input
    id: author
    attributes:
      label: Author
      description: Add-on authors
      placeholder: Jon Doe
    validations:
      required: true
