name: Check submitted NVDA add-on

on:
  issues:
    types:
      - opened
      - edited

jobs:

  checkMetadata:
  
    runs-on: windows-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python 3.7 x86
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
        architecture: x86
    - name: Checkout validate add-on metadata
      uses: actions/checkout@v2    
      with:
        repository: nvdaes/validateNvdaAddonMetadata
        ref: addonFiles
        path: validate
    - name: Validate metadata
      run: |
        runvalidate https://github.com/nvdaes/clipContentsDesigner/releases/download/14.0/clipContentsDesigner-14.0.nvda-addon
      shell: cmd
